-- 创建基础邮件服务配置表
CREATE TABLE IF NOT EXISTS smtp_config (
  id INT AUTO_INCREMENT PRIMARY KEY,
  smtp_host VARCHAR(255) NOT NULL COMMENT 'SMTP服务器地址',
  smtp_port INT NOT NULL COMMENT 'SMTP端口',
  smtp_user VARCHAR(255) NOT NULL COMMENT '发件人邮箱',
  smtp_password VARCHAR(255) NOT NULL COMMENT '邮箱密码或授权码',
  is_active BOOLEAN DEFAULT TRUE COMMENT '是否启用',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='基础邮件服务配置表';